@extends('layouts.app')
@section('title', 'Přidat fotku na mapu — Slepé Slunce')
@push('head')<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" crossorigin="">@endpush
@section('content')
<div class="quick-route-page"><div class="quick-route-shell"><p class="eyebrow ink">Expediční dispečink</p><h1>Přidat fotku na mapu</h1><p>Fotografie se zveřejní okamžitě. Bez načtení GPS se použije poloha aktivní etapy.</p>
@if(session('message'))<div class="quick-message">{{ session('message') }}</div>@endif @if($errors->any())<div class="quick-errors"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form class="quick-route-form" method="post" enctype="multipart/form-data" action="{{ route('tracking.photo.store') }}">@csrf<label>Fotografie<input name="image" type="file" accept="image/*" capture="environment" required></label><label>Alternativní popis fotografie<input name="alt" required maxlength="300" placeholder="Co je na fotografii pro člověka, který ji nevidí"></label><label>Popisek <span>(nepovinný)</span><textarea name="caption" rows="3" maxlength="500"></textarea></label><button class="button button-quiet location-button" type="button" id="detect-location">Použít polohu telefonu</button><p id="location-status" class="location-status" aria-live="polite">{{ $position ? 'Bez načtení GPS použijeme polohu aktivní etapy.' : 'Je potřeba načíst polohu.' }}</p><div id="photo-location-map" class="photo-location-map" aria-label="Vyberte polohu fotografie kliknutím do mapy"></div><p class="map-note">Kliknutím do mapy můžete polohu ručně upřesnit.</p><div class="coordinate-grid"><label>Šířka<input id="latitude" name="latitude" inputmode="decimal"></label><label>Délka<input id="longitude" name="longitude" inputmode="decimal"></label></div><button class="button button-primary" type="submit">Zveřejnit fotografii</button></form><p class="quick-back"><a href="{{ url('/admin') }}">← Zpět na nástěnku</a></p></div></div>
@endsection
@push('scripts')<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" crossorigin=""></script><script>
const button=document.getElementById('detect-location'),status=document.getElementById('location-status'),lat=document.getElementById('latitude'),lon=document.getElementById('longitude');const initial={{ Illuminate\Support\Js::from($position) }},map=L.map('photo-location-map').setView(initial?[initial.latitude,initial.longitude]:[48,10],initial?10:5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);let marker=initial?L.marker([initial.latitude,initial.longitude]).addTo(map):null;const setPosition=(latitude,longitude,zoom=false)=>{lat.value=Number(latitude).toFixed(7);lon.value=Number(longitude).toFixed(7);if(marker)marker.setLatLng([latitude,longitude]);else marker=L.marker([latitude,longitude]).addTo(map);if(zoom)map.setView([latitude,longitude],15)};map.on('click',event=>{setPosition(event.latlng.lat,event.latlng.lng);status.textContent='Poloha byla ručně vybrána v mapě.'});button.addEventListener('click',()=>{if(!navigator.geolocation){status.textContent='Tento prohlížeč neumí zjistit polohu.';return}button.disabled=true;status.textContent='Zjišťuji polohu…';navigator.geolocation.getCurrentPosition(p=>{setPosition(p.coords.latitude,p.coords.longitude,true);status.textContent=`GPS načtena, přesnost přibližně ${Math.round(p.coords.accuracy)} m.`;button.disabled=false},()=>{status.textContent='GPS se nepodařilo načíst; použije se aktivní etapa.';button.disabled=false},{enableHighAccuracy:true,timeout:15000,maximumAge:60000})});
</script>@endpush
